import React, { useState, useMemo } from 'react';
import { useWatchlist } from '../WatchlistContext';
import { 
    ComposedChart, Area, XAxis, YAxis, CartesianGrid, Tooltip as RechartsTooltip, ResponsiveContainer,
    BarChart, Bar, Line
} from 'recharts';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { useToast } from '../ToastContext';

export default function PortfolioManager({ onBack }) {
    const { watchlist, getWatchlistStats } = useWatchlist();
    const toast = useToast();
    const [liquidCapital, setLiquidCapital] = useState(5000000); // Default $5M
    const [isGenerating, setIsGenerating] = useState(false);

    // Calculate aggregated stats
    const metrics = useMemo(() => {
        if (watchlist.length === 0) return { totalValue: 0, mktCap: 0, avgYield: 0, highVol: 0 };
        const totalValue = watchlist.reduce((sum, item) => sum + (item.zhvi || 350000), 0);
        const mktCap = totalValue * 0.7; // Estimated MAB aggregation
        
        return {
            totalValue,
            mktCap,
            avgYield: 18.5, // Blended aggregate yield proxy
            highVol: watchlist.filter(w => w.priority === 'high').length
        };
    }, [watchlist]);

    // Calculate 36 month compounded growth projection
    const growthData = useMemo(() => {
        const data = [];
        let currentEquity = liquidCapital;
        for (let month = 0; month <= 36; month += 6) {
            data.push({
                month: month === 0 ? 'Now' : `${month}M`,
                capital: currentEquity,
                projectedReturns: currentEquity * (1 + (metrics.avgYield / 100) * (month / 12)),
            });
        }
        return data;
    }, [liquidCapital, metrics]);

    // Handle PDF Generation
    const generateProspectus = () => {
        if (watchlist.length === 0) {
            toast.showError('Watchlist is Empty', 'Add properties to your Watchlist to generate a prospectus.');
            return;
        }

        setIsGenerating(true);

        try {
            const doc = new jsPDF('landscape');
            
            // Header
            doc.setFillColor(30, 58, 138); // Blue-900
            doc.rect(0, 0, 300, 30, 'F');
            doc.setTextColor(255, 255, 255);
            doc.setFontSize(24);
            doc.setFont("helvetica", "bold");
            doc.text("AUCTION INTEL", 14, 20);
            
            doc.setFontSize(12);
            doc.setFont("helvetica", "normal");
            doc.text("Institutional Investment Prospectus - Real Estate Tax Assets", 100, 20);

            // Portfolio Overview Box
            doc.setTextColor(0, 0, 0);
            doc.setFontSize(16);
            doc.setFont("helvetica", "bold");
            doc.text("Portfolio Aggregate Summary", 14, 45);

            doc.setFontSize(11);
            doc.setFont("helvetica", "normal");
            doc.text(`Total Liquid Capital Target: $${liquidCapital.toLocaleString()}`, 14, 55);
            doc.text(`Estimated Market Cap (MAB): $${metrics.mktCap.toLocaleString()}`, 14, 62);
            doc.text(`Blended Target Yield: ${metrics.avgYield}% ROI`, 14, 69);
            doc.text(`Tracked Assets: ${watchlist.length} Counties`, 14, 76);

            // Table of selected assets
            const tableData = watchlist.map(item => [
                item.county,
                item.stateAbbr,
                `T${item.tier}`,
                `$${(item.zhvi || 0).toLocaleString()}`,
                `$${(item.mabThreshold || (item.zhvi * 0.7)).toLocaleString()}`,
                item.priority.toUpperCase()
            ]);

            autoTable(doc, {
                startY: 85,
                head: [['Target County', 'State', 'Risk Tier', 'Est. ARV', 'Allocated MAB Threshold', 'Priority']],
                body: tableData,
                theme: 'striped',
                headStyles: { fillColor: [30, 58, 138] },
                styles: { fontSize: 10, cellPadding: 4 },
                alternateRowStyles: { fillColor: [241, 245, 249] }
            });

            // Footer
            const pageCount = doc.internal.getNumberOfPages();
            for (let i = 1; i <= pageCount; i++) {
                doc.setPage(i);
                doc.setFontSize(8);
                doc.setTextColor(150);
                doc.text(
                    `Generated by Auction Intel Algorithmic Underwriting Engine | Page ${i} of ${pageCount}`,
                    14,
                    doc.internal.pageSize.height - 10
                );
            }

            doc.save(`Auction_Intel_Prospectus_${new Date().toISOString().split('T')[0]}.pdf`);
            toast.showSuccess('Prospectus Generated', 'Your PDF investment report has been downloaded successfully.');
        } catch (error) {
            console.error("PDF Generation Failed:", error);
            toast.showError('Generation Failed', 'There was an error generating the PDF prospectus.');
        } finally {
            setIsGenerating(false);
        }
    };

    return (
        <div className="bg-canvas rounded-md shadow-none border border-slate-200 overflow-hidden h-full flex flex-col">
            {/* Header */}
            <div className="p-8 bg-surface text-white flex justify-between items-center shrink-0">
                <div>
                    <div className="flex items-center gap-3 mb-1">
                        <span className="text-lg font-mono">💼</span>
                        <h2 className="text-xl font-mono font-semibold tracking-tighter">Fund Manager</h2>
                    </div>
                    <p className="text-indigo-200 text-xs font-bold uppercase tracking-widest">
                        Portfolio Capital Allocation & Risk Aggregation
                    </p>
                </div>
                <div className="flex items-center gap-3">
                    <button 
                        onClick={generateProspectus}
                        disabled={isGenerating || watchlist.length === 0}
                        className={`bg-emerald-500 hover:bg-emerald-400 text-white px-6 py-3 rounded-sm text-sm font-semibold transition-all shadow-none flex items-center gap-2 ${
 isGenerating || watchlist.length === 0 ? 'opacity-50 cursor-not-allowed' : ''
 }`}
                    >
                        {isGenerating ? '⏳ Compiling PDF...' : '📄 Generate Prospectus'}
                    </button>
                    {onBack && (
                        <button onClick={onBack} className="bg-slate-100/60 hover:bg-slate-50/20 px-4 py-3 rounded-sm text-xs font-bold transition-all border border-white/20">
                            ← Back
                        </button>
                    )}
                </div>
            </div>

            <div className="flex-1 overflow-auto p-8 bg-surface">
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                    
                    {/* Capital Inputs */}
                    <div className="lg:col-span-1 space-y-6">
                        <div className="bg-canvas rounded-md p-8 border border-slate-300 shadow-none">
                            <h3 className="text-sm font-semibold text-slate-600 uppercase tracking-widest mb-6">Asset Allocation</h3>
                            
                            <label className="block text-xs font-bold text-slate-700 mb-2">Total Liquid Capital Constraint</label>
                            <div className="relative mb-8">
                                <span className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-500 font-semibold">$</span>
                                <input 
                                    type="number"
                                    value={liquidCapital}
                                    onChange={(e) => setLiquidCapital(Number(e.target.value))}
                                    className="w-full pl-8 pr-4 py-4 bg-surface border-2 border-slate-300 rounded-sm text-lg font-semibold text-slate-900 focus:ring-4 focus:ring-indigo-100 focus:border-indigo-500 transition-all"
                                />
                            </div>

                            <div className="space-y-4">
                                <div className="p-4 bg-indigo-50 border border-indigo-100 rounded-md flex justify-between items-center">
                                    <div className="text-[10px] font-semibold text-indigo-400 uppercase tracking-widest">Est. Market Cap Need</div>
                                    <div className="text-lg font-semibold text-indigo-700">${(metrics.mktCap).toLocaleString()}</div>
                                </div>
                                <div className="p-4 bg-emerald-50 border border-emerald-100 rounded-md flex justify-between items-center">
                                    <div className="text-[10px] font-semibold text-emerald-600 uppercase tracking-widest">Blended Yield Target</div>
                                    <div className="text-lg font-semibold text-emerald-700">{metrics.avgYield}%</div>
                                </div>
                                <div className="p-4 bg-surface border border-slate-300 rounded-md flex justify-between items-center">
                                    <div className="text-[10px] font-semibold text-slate-500 uppercase tracking-widest">Tracked Assets</div>
                                    <div className="text-lg font-semibold text-slate-900">{watchlist.length} Deals</div>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Yield Projections */}
                    <div className="lg:col-span-2 space-y-6">
                        <div className="bg-canvas rounded-md p-8 border border-slate-300 shadow-none h-[400px] flex flex-col">
                            <div className="flex justify-between items-center mb-6 shrink-0">
                                <h3 className="text-lg font-semibold text-slate-900 tracking-tight">Compounded Equity Growth</h3>
                                <div className="flex gap-4">
                                    <div className="flex items-center gap-2 text-[10px] font-semibold uppercase text-slate-500"><span className="w-2 h-2 rounded-sm bg-indigo-600"></span> Projected Returns</div>
                                    <div className="flex items-center gap-2 text-[10px] font-semibold uppercase text-slate-500"><span className="w-2 h-2 rounded-sm bg-slate-300"></span> Baseline Capital</div>
                                </div>
                            </div>
                            
                            <div className="flex-1 min-h-0">
                                <ResponsiveContainer width="100%" height="100%">
                                    <ComposedChart data={growthData} margin={{ top: 10, right: 10, left: 20, bottom: 0 }}>
                                        <defs>
                                            <linearGradient id="colorYield" x1="0" y1="0" x2="0" y2="1">
                                                <stop offset="5%" stopColor="#4f46e5" stopOpacity={0.15}/>
                                                <stop offset="95%" stopColor="#4f46e5" stopOpacity={0}/>
                                            </linearGradient>
                                        </defs>
                                        <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#E2E8F0" />
                                        <XAxis dataKey="month" stroke="#94A3B8" fontSize={10} fontWeight="bold" tickLine={false} axisLine={false} />
                                        <YAxis 
                                            stroke="#94A3B8" 
                                            fontSize={10} 
                                            fontWeight="bold" 
                                            tickLine={false} 
                                            axisLine={false} 
                                            tickFormatter={(val) => `$${(val / 1000000).toFixed(1)}M`} 
                                        />
                                        <RechartsTooltip 
                                            formatter={(value) => [`$${value.toLocaleString()}`, 'Portfolio Value']}
                                            contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1)' }}
                                        />
                                        <Area type="monotone" dataKey="projectedReturns" stroke="#4f46e5" strokeWidth={3} fillOpacity={1} fill="url(#colorYield)" />
                                        <Line type="monotone" dataKey="capital" stroke="#CBD5E1" strokeWidth={2} strokeDasharray="5 5" dot={false} />
                                    </ComposedChart>
                                </ResponsiveContainer>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    );
}
